galaxy_info:
  author: Takahiro Yamaki
  description: Tomcat 8 for CnetOS/RHEL 7
  license: Apache-2.0
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - tomcat
    - development
dependencies:
  - java
