---
# vars file for tomcat-8

tomcat_service_name: tomcat

tomcat_user:  tomcat
tomcat_group: tomcat

tomcat_install_path: /opt
tomcat_catalina_out_path: "{{ tomcat_log_dir }}/catalina.log"

tomcat_major_version:   "{{ tomcat_version.split('.')[0].tomcat_version.split('.')[1] }}"
template_server_xml: "server-{{ '.'.join(tomcat_version.split('.')[:2]) }}.xml.j2"

tomcat_listen_address: 0.0.0.0

tomcat_download_URL: https://archive.apache.org/dist
tomcat_download_dir: /var/tmp/downloads
tomcat_log_dir:      /var/log/tomcat
tomcat_pid_dir:      /var/run/tomcat
tomcat_instances_dir: /var/lib/tomcats

tomcat_unnecessary_default_apps:
  # - ROOT
  - docs
  - examples
  - host-manager
  - manager
