---
# vars file for tomcat-8

tomcat_service_name: tomcat

tomcat_user:  tomcat
tomcat_group: tomcat

tomcat_install_path: /opt

tomcat_major_version:   "{{ tomcat_version.split('.')[0].tomcat_version.split('.')[1] }}"
tomcat_template_server: "tomcat-server-{{ '.'.join(tomcat_version.split('.')[:2]) }}.xml.j2"

tomcat_listen_address: 0.0.0.0

tomcat_download_URL: https://archive.apache.org/dist
tomcat_download_dir: /tmp/downloads

tomcat_unnecessary_default_apps:
  - ROOT
  - docs
  - examples
  - host-manager
  - manager
